---

include:
  - project: veepee/vptech/sre/iac/ci-cd/docker-lint
    ref: 1.0.0
    file: gitlab-ci-lint.yml
  - project: veepee/vptech/sre/iac/ci-cd/docker-build
    ref: 4.2.0
    file: gitlab-ci-build.yml
  - project: veepee/vptech/sre/iac/ci-cd/markdown-lint
    ref: 1.2.0
    file: gitlab-ci.yml
  - project: veepee/vptech/sre/iac/ci-cd/semantic-release
    ref: 2.6.0
    file: gitlab-ci.yml

variables:
  APP_NAME: molecule
  DOCKER_PUBLIC_REGISTRY_URL: docker.io
  DOCKER_PUBLIC_REGISTRY_USERNAME: ${PUBLIC_REGISTRY_USERNAME}
  DOCKER_PUBLIC_REGISTRY_PASSWORD: ${PUBLIC_REGISTRY_PASSWORD}
  DOCKER_PUBLIC_REPO: vptech
  PUBLIC: 'true'

stages:
    - lint
    - build
    - test
    - publish
    - release

build:v3.0.4:
  extends: .build:docker
  variables:
    MOLECULE_VERSION: 3.0.4
    TAG: 3.0.4

build:v3.0.5:
  extends: .build:docker
  variables:
    MOLECULE_VERSION: 3.0.5
    TAG: 3.0.5 latest

publish:v3.0.4:
  extends: .publish:docker
  variables:
    TAG: 3.0.4

publish:v3.0.5:
  extends: .publish:docker
  variables:
    TAG: 3.0.5 latest

public:v3.0.4:
  extends: .publish-public:docker
  variables:
    TAG: 3.0.4

public:v3.0.5:
  extends: .publish-public:docker
  variables:
    TAG: 3.0.5 latest
...
