---
stages:
  - lint
  - build
  - publish
  - release

include:
  - project: veepee/vptech/sre/iac/ci-cd/markdown-lint
    ref: 1.2.0
    file: gitlab-ci.yml
  - project: veepee/vptech/sre/iac/ci-cd/docker-lint
    ref: 2.0.1
    file: gitlab-ci.yml
  - project: veepee/vptech/sre/iac/ci-cd/docker-build
    ref: feat/delete_multi_tags
    file: gitlab-ci-build.yml
  - project: veepee/vptech/sre/iac/ci-cd/semantic-release
    ref: 2.9.0
    file: gitlab-ci.yml

variables:
  APP_NAME: molecule
  DOCKER_PUBLIC_REPO: vptech
  PUBLIC: 'true'
  SEMANTIC_CONFIG_FILE: changelog

## Feature build / publish / delete

publish-feature:docker:
  variables:
    DOCKER_BUILD_ARGS: --build-arg MOLECULE_VERSION=${TAG}
  parallel:
    matrix:
      - NAME: ['test']
        TAG: ['2.22','3.0.4','3.0.5','3.0.6']

delete-feature:docker:
  variables:
    TAG: '2.22 3.0.4 3.0.5 3.0.6'

## Public publish

publish-public-release:docker:
  variables:
    DOCKER_BUILD_ARGS: --build-arg MOLECULE_VERSION=${TAG}
  parallel:
    matrix:
      - NAME: ['test']
        TAG: ['2.22','3.0.4','3.0.5','3.0.6']
...
