---
stages:
  - lint
  - build
  - publish
  - release

include:
  - project: veepee/vptech/sre/iac/ci-cd/markdown-lint
    ref: 1.2.0
    file: gitlab-ci.yml
  - project: veepee/vptech/sre/iac/ci-cd/docker-lint
    ref: 2.0.1
    file: gitlab-ci.yml
  - project: veepee/vptech/sre/iac/ci-cd/docker-build
    ref: 4.2.3
    file: gitlab-ci-build.yml
  - project: veepee/vptech/sre/iac/ci-cd/semantic-release
    ref: 2.9.0
    file: gitlab-ci.yml

variables:
  APP_NAME: molecule
  DOCKER_DISABLE_ALL_JOBS: 'true'
  DOCKER_PUBLIC_REPO: vptech
  PUBLIC: 'true'
  SEMANTIC_CONFIG_FILE: changelog

public:v2.22:
  extends: .publish-public:docker
  variables:
    DOCKER_BUILD_ARGS: --build-arg MOLECULE_VERSION=2.22
    TAG: '2.22'

public:v3.0.4:
  extends: .publish-public:docker
  variables:
    DOCKER_BUILD_ARGS: --build-arg MOLECULE_VERSION=3.0.4
    TAG: 3.0.4

public:v3.0.5:
  extends: .publish-public:docker
  variables:
    DOCKER_BUILD_ARGS: --build-arg MOLECULE_VERSION=3.0.5
    TAG: 3.0.5

public:v3.0.6:
  extends: .publish-public:docker
  variables:
    DOCKER_BUILD_ARGS: --build-arg MOLECULE_VERSION=3.0.6
    TAG: 3.0.6 latest
...
