---

include:
  - project: veepee/vptech/sre/iac/ci-cd/docker-lint
    ref: 1.0.0
    file: gitlab-ci-lint.yml
  - project: veepee/vptech/sre/iac/ci-cd/docker-build
    ref: 4.2.0
    file: gitlab-ci-build.yml
  - project: veepee/vptech/sre/iac/ci-cd/markdown-lint
    ref: 1.2.0
    file: gitlab-ci.yml
  - project: veepee/vptech/sre/iac/ci-cd/semantic-release
    ref: 2.6.0
    file: gitlab-ci.yml

variables:
  APP_NAME: molecule
  DOCKER_PUBLIC_REGISTRY_URL: docker.io
  DOCKER_PUBLIC_REGISTRY_USERNAME: ${PUBLIC_REGISTRY_USERNAME}
  DOCKER_PUBLIC_REGISTRY_PASSWORD: ${DOCKER_PUBLIC_REGISTRY_PASSWORD}
  DOCKER_PUBLIC_REPO: vptech
  PUBLIC: true

stages:
    - lint
    - build
    - test
    - publish
    - release

.build:
  stage: build
  image: docker:latest
  artifacts:
    expire_in: 1 day
    paths:
      - image
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  tags:
    - dind
  before_script:
    - docker login -u "${PUBLIC_REGISTRY_USERNAME}" -p "${PUBLIC_REGISTRY_PASSWORD}"

build:v2.22:
  extends: .build:docker:master
  variables:
    MOLECULE_VERSION: 2.22
    TAG: 2.22

build:v3.0.4:
  extends: .build:docker:master
  variables:
    MOLECULE_VERSION: 3.0.4
    TAG: 3.0.4

build:v3.0.5:
  extends: .build:docker:master
  variables:
    MOLECULE_VERSION: 3.0.5
    TAG: 3.0.5 latest

publish:v2.22:
  extends: .publish:docker:master
  variables:
    TAG: 2.22

publish:v3.0.4:
  extends: .publish:docker:master
  variables:
    TAG: 3.0.4

publish:v3.0.5:
  extends: .publish:docker:master
  variables:
    TAG: 3.0.5 latest
...
